name: SingleTetris
main: me.kenandwicky.tetris.Tetris
author: KenKwokandWickyYiu
description: A funny Tetris Game with Singal Player
version: 1.0
api-version: 1.13

commands:
  givebanner:
   usage: /<command>
   description: Give player a custom Banner
  settetris:
   usage: /<command>
   description: To build the tetris
  initializetetris:
   usage: /<command>
   description: Setting
  re:
   usage: /<command>
   description: Settingsss
  next:
   usage: /<command>
   description: Test
  hold:
   usage: /<command>
   description: Test
  start:
   usage: /<command>
   description: Start
  getposition:
   usage: /<command>
   description: test
  gamenext:
   usage: /<command>
   description: test 
  gamestart:
   usage: /<command>
   description: test   
   
  
  